### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by zmaril** [sunlightlabs/parmenides#9]
Moxie always ends it's job by reporting a json parse error stack trace from clojure. Ideally this shouldn't happen.

**Comment by zmaril** [comment]
```clojure
Posting...
java.io.EOFException: JSON error (end-of-file)
	at clojure.data.json$_read.invoke(json.clj:182)
	at clojure.data.json$read.doInvoke(json.clj:272)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:628)
	at clojure.data.json$read_str.doInvoke(json.clj:278)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at parmenides.core$ingest.invoke(core.clj:21)
	at parmenides.core$fn__21319.invoke(core.clj:27)
	at compojure.core$make_route$fn__5409.invoke(core.clj:104)
	at compojure.core$wrap_route_middleware$fn__5405.invoke(core.clj:94)
	at compojure.core$if_route$fn__5387.invoke(core.clj:41)
	at compojure.core$if_method$fn__5379.invoke(core.clj:27)
	at compojure.core$routing$fn__5415.invoke(core.clj:118)
	at clojure.core$some.invoke(core.clj:2560)
	at compojure.core$routing.doInvoke(core.clj:118)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:628)
	at compojure.core$routes$fn__5419.invoke(core.clj:123)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__6398.invoke(keyword_params.clj:35)
	at ring.middleware.params$wrap_params$fn__6628.invoke(params.clj:64)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__6746.invoke(absolute_redirects.clj:36)
	at ring.middleware.content_type$wrap_content_type$fn__6723.invoke(content_type.clj:30)
	at ring.middleware.not_modified$wrap_not_modified$fn__6704.invoke(not_modified.clj:44)
	at aleph.http.server$wrap_stream__GT_input_stream$fn__18703.invoke(server.clj:390)
	at aleph.http.server$handle_request$fn__18632$fn__18633.invoke(server.clj:148)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:49)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by zmaril** [comment]
[Fixed](https://github.com/sunlightlabs/parmenides/commit/10a63bc). Cannot slurp things twice.
